plugin:
  enable: true
  prefix: "&7[&eLootBox&7] "
  usage: "&cUtilisation: /basiklootbox pseudo nombre-de-box"
message:
  player-open-box: "&c Attention ! Vous ouvrez une loot box !"
  admin-give-offline-player: "&cLe joueur {player} n'est pas connecter :/"
  admin-give-online-player: "&cVous venez de give {box_count} box à {player}"
  player-receive-box: "&cVous venez de recevoir {box_count} box !"
lootbox:
  item-name: 'BEACON'
  name: "&b&lBASIK&f&lLOOT&4&lBOX"
  glow: true
  lores:
    - "&7Pose la lootbox sur une surface plate"
    - "&e&l Rareté: &l○○○&r○○"
  how-much-loot: 5
  rewards:
    dirt:
      item-name: DIRT
      percent: 20
      name: "&dMagicDirt"
      lore:
        - "&d&lthis is a magic dirt block"
      how-much: 1
    WOOL:
      item-name: WOOL
      percent: 80
      name: "&bMagicWool"
      lore:
        - "&b&lthis is a magic Wool block"
      how-much: 60


